swagger: '3.0'
info:
  title: Stop light Demo
  version: '1.0'
  description: This gateway connects to various serveless services developed by ECE-EE-Galileo
  contact:
    email: ece.ee.services.galileo@autodesk.com
    name: ECE EE Services Galileo
    url: 'https://wiki.autodesk.com/x/_HGvKQ'
contact:
  name: Stoplight demo
  email: nari.kolla@gmail.com
paths:
  '/users/{usedId}':
    get:
      responses:
        '200':
          description: Success Response when the information is retrieved successfully from ABN
          headers:
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: boolean
          schema:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
              email:
                type: string
              mobile:
                type: number
            required:
              - id
              - name
              - email
              - mobile
          examples:
            user1:
              id: 1111
              name: Narendra Kolla
              email: nari.kolla@gmail.com
              mobile: 1111111111
            user2:
              id: 2222
              name: John Deo
              email: John.Doe@gmail.com
              mobile: 22222222222
        '400':
          description: The error is returned when there is an issue with the arguments of the request.
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
            required:
              - code
              - message
          examples:
            BadRequest:
              code: 400
              message: Bad Request
        '401':
          description: UnAuthorized to user Service.
          headers:
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Credentials:
              type: boolean
        '404':
          description: The error is returned when there no data found .
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
            required:
              - code
              - message
        '500':
          description: The error is returned when there is an issue with the processing of the request.
          schema:
            type: object
            properties:
              code:
                type: number
              message:
                type: string
            required:
              - code
              - message

      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mss-australian-business-numbers-lookup/invocations'
        requestParameters:
          integration.request.path.taxNumber: method.request.path.taxNumber
          integration.request.querystring.mockDependencies: method.request.querystring.mockDependencies
        responses:
          '200':
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,jwToken,X-Amz-Date,Authorization,X-Api-Key'''
              method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS,POST'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
              method.response.header.Access-Control-Allow-Credentials: false
          '401':
            statusCode: '401'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,jwToken,X-Amz-Date,Authorization,X-Api-Key'''
              method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS,POST'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
              method.response.header.Access-Control-Allow-Credentials: false
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
      summary: Validate phone numbers from ABN
      operationId: abn
      produces:
        - application/json
      consumes:
        - application/json
      tags:
        - abn
      parameters:
        - type: string
          name: taxNumber
          in: path
          required: true
          description: ABN Tax Number
        - type: boolean
          name: mockDependencies
          in: query
      x-internal: false
      description: ''
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
        - CORS
      responses:
        '200':
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Allow-Credentials:
              type: string
      security:
        - NONE: []
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: '''Content-Type,jwToken,Authorization,X-Api-Key'''
              method.response.header.Access-Control-Allow-Methods: '''GET,OPTIONS,POST'''
              method.response.header.Access-Control-Allow-Origin: '''*'''
              method.response.header.Access-Control-Allow-Credentials: false
            responseTemplates:
              application/json: |
                {}
        passthroughBehavior: when_no_match
        httpMethod: OPTIONS

schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: users

